language: node_js

node_js:
  - 'stable'

branches:
  only:
    - master

cache:
  directories:
    - node_modules

before_script:
  - 'npm i -g gatsby-cli'
  - 'yarn'

script:
  - yarn deploy

env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
